### ISSUE TITLE
Feature Request: Array support

### ISSUE THREAD

**Issue by op8867555** [Jij-Inc/pyo3-stub-gen#57]
Hi,
Thank you for releasing this convenient crate, I just tried it and figured out array is not supported yet.

BTW, Is it possible to provide a `gen_stub`-wrapped version of `pyclass`, `pymethods`, `pyfunction` that acts like a drop-in replacement?

**Comment by termoshtt** [comment]
Maybe "array" means https://docs.python.org/3/library/array.html

> the trait PyStubType is not implemented for Option<T> (where T does implement PyStubType)

This is done https://docs.rs/pyo3-stub-gen/latest/pyo3_stub_gen/trait.PyStubType.html#impl-PyStubType-for-Option%3CT%3E

> the trait PyStubType is not implemented for &[u8]

This case is difficult since we cannot use specialization. Since we already have `impl<T: PyStubType> PyStubType for Vec<T>`, we cannot implements `impl PyStubType for Vec<u8>`. We can avoid this by using `PyBytes` instead. Same thing for slice.

> the trait PyStubType is not implemented for &T (where T does implement PyStubType)

This is simply lacking.

**Comment by op8867555** [comment]
Sorry, I didn't make it clear. I mean the rust array (e.g. `[T; N]`) which will be [convert](https://github.com/PyO3/pyo3/blob/57d85b1f8b511d1e3daa16141f266eeca2d7eadd/src/conversions/std/array.rs#L11) to `list[T]` in the python world.

**Comment by michaeljones** [comment]
> > the trait PyStubType is not implemented for &T (where T does implement PyStubType)
> 
> This is simply lacking.

Sorry for the slow follow up. When you say "This is simply lacking", does that mean it is something that could be added to this tool or am I thinking about the issue incorrectly and I should explore another approach?
